//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTableTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public long CustomerId { get; set; }
        public string Surname { get; set; }
        public string MiddleName { get; set; }
        public string FirstName { get; set; }
        public byte GenderId { get; set; }
        public byte TitleId { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public byte StateId { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string PassportNo { get; set; }
        public string IdentificationPath { get; set; }
        public string Occupation { get; set; }
        public byte MaritalStatusId { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime DateTimeAdded { get; set; }
        public string Nationality { get; set; }
        public bool PreExistingMedicalCondition { get; set; }
        public string MedicalCondition { get; set; }
        public Nullable<bool> SanctionFlag { get; set; }
    }
}
